---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  
  tasks:
  - name: Create new file under /tmp
    file:
      path: /tmp/ansibletestfile.txt
      state: touch
      owner: atuser
      group: atuser
      
  - name: Pull new file to AT server
    fetch:
      src: /tmp/ansibletestfile.txt
      dest: /home/admin
      flat: yes
